-- File: toplevel.vhd
-- Generated by MyHDL 0.11
-- Date: Mon Jul  4 13:30:38 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity toplevel is
    port (
        LEDR: out unsigned(9 downto 0);
        SW: in unsigned(9 downto 0);
        KEY: in unsigned(3 downto 0);
        HEX0: in unsigned(4 downto 0);
        HEX1: in unsigned(4 downto 0);
        HEX2: in unsigned(4 downto 0);
        HEX3: in unsigned(4 downto 0);
        HEX4: in unsigned(4 downto 0);
        HEX5: in unsigned(4 downto 0)
    );
end entity toplevel;


architecture MyHDL of toplevel is




begin





LEDR(0) <= stdl(bool(SW(0)) and (not bool(SW(1))));

end architecture MyHDL;
