-- File: toplevel.vhd
-- Generated by MyHDL 0.11
-- Date: Wed Jul 13 19:29:32 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity toplevel is
    port (
        LEDR: out unsigned(9 downto 0);
        SW: in unsigned(9 downto 0);
        KEY: in unsigned(3 downto 0);
        HEX0: out unsigned(6 downto 0);
        HEX1: out unsigned(6 downto 0);
        HEX2: in unsigned(6 downto 0);
        HEX3: in unsigned(6 downto 0);
        HEX4: in unsigned(6 downto 0);
        HEX5: in unsigned(6 downto 0)
    );
end entity toplevel;


architecture MyHDL of toplevel is




begin




TOPLEVEL_EXE50_COMB: process (SW) is
begin
    LEDR(0) <= SW(0);
    LEDR(1) <= (SW(0) and SW(1));
    LEDR(2) <= stdl((not bool(SW(0))));
    LEDR(3) <= (SW(0) xor SW(1));
    for i in 4 to 10-1 loop
        LEDR(i) <= '1';
    end loop;
end process TOPLEVEL_EXE50_COMB;

TOPLEVEL_SW2HEX0_COMB: process (SW) is
begin
    for i in 0 to 7-1 loop
        HEX0(i) <= SW(i);
    end loop;
end process TOPLEVEL_SW2HEX0_COMB;

TOPLEVEL_BIN2HEX0_COMB: process (SW) is
begin
    if (SW(4-1 downto 0) = 0) then
        HEX1 <= unsigned'("1000000");
    elsif (SW(4-1 downto 0) = 1) then
        HEX1 <= unsigned'("1111001");
    elsif (SW(4-1 downto 0) = 2) then
        HEX1 <= unsigned'("0100100");
    elsif (SW(4-1 downto 0) = 3) then
        HEX1 <= unsigned'("0110000");
    elsif (SW(4-1 downto 0) = 4) then
        HEX1 <= unsigned'("0011001");
    elsif (SW(4-1 downto 0) = 5) then
        HEX1 <= unsigned'("0010010");
    elsif (SW(4-1 downto 0) = 6) then
        HEX1 <= unsigned'("0000010");
    elsif (SW(4-1 downto 0) = 7) then
        HEX1 <= unsigned'("1111000");
    elsif (SW(4-1 downto 0) = 8) then
        HEX1 <= unsigned'("0000000");
    elsif (SW(4-1 downto 0) = 9) then
        HEX1 <= unsigned'("0011000");
    elsif (SW(4-1 downto 0) = 10) then
        HEX1 <= unsigned'("0001000");
    elsif (SW(4-1 downto 0) = 11) then
        HEX1 <= unsigned'("0000011");
    elsif (SW(4-1 downto 0) = 12) then
        HEX1 <= unsigned'("1000110");
    elsif (SW(4-1 downto 0) = 13) then
        HEX1 <= unsigned'("0100001");
    elsif (SW(4-1 downto 0) = 14) then
        HEX1 <= unsigned'("0000110");
    else
        HEX1 <= unsigned'("0001110");
    end if;
end process TOPLEVEL_BIN2HEX0_COMB;

end architecture MyHDL;
